### ISSUE TITLE
useId support

### ISSUE THREAD

**Issue by chrstntdd** [preactjs/preact-ssr-prepass#46]
The latest version of preact added a much appreciated `useId` hook.

When using `preact-ssr-prepass`, `preact-render-to-string`, and `useId` in a typical SSR setup as outlined in the docs, `preact` throws this error within the `useId` function.

```
TypeError: Cannot read properties of undefined (reading 'length')
```

Looking into the source, it seems that the mangled `_mask` property on the vnode (`__v` ?) is undefined. 

```hooks.mjs
function b() {
	var n = p(r++, 11);
	return (
		n.__ ||
			(n.__ =
				'P' +
				(function (n) {
                                          console.log({n, u: u.__v}); // n is undefined
					for (var t = 0, r = n.length; r > 0; )
						t = ((t << 5) - t + n.charCodeAt(--r)) | 0;
					return t;
				})(u.__v.o) +
				r),
		n.__
	);
}
```

Is this expected? 

---

Dependencies:
```
"@preact/signals": "^1.0.4",
"preact": "^10.11.0",
"preact-render-to-string": "^5.2.4",
"preact-ssr-prepass": "^1.2.0"
```

**Comment by JoviDeCroock** [comment]
We will probably need a similar PR to https://github.com/preactjs/preact-render-to-string/pull/237
