### ISSUE TITLE
Release patch with fix exports field

### ISSUE THREAD

**Issue by aleksandrjet** [preactjs/preact-ssr-prepass#57]
Could you please release a patch to fix the export field in `package.json`? Unfortunately, this package cannot be used with the settings in `tsconfig.json`: `module: "Node16", ModuleResolution: "Node16"`

It was fixed here https://github.com/preactjs/preact-ssr-prepass/pull/56

**Comment by rschristian** [comment]
Sorry for the delay, I apparently wasn't set to watch the repo
